### ISSUE TITLE
[enhancement] <提交拦截域名>

### ISSUE THREAD

**Issue by wudaodadi** [TG-Twilight/AWAvenue-Ads-Rule#105]
### 域名

abtest3-misc-lf.zijieapi.com
ad.doubleclick.net
ad.xiaomi.com
ad1.xiaomi.com
analytics-api.bauhaus.fi
analytics.finansforbundet.se
analytics-fe.digital-cloud-eu-main.medallia.eu
analytics.hostup.se
analitica.potencia.pro
analytics.phplist.com
analytics.lookingforways.com
analytics.nicobonx.com
applog.snssdk.com
appcfg.v.qq.com
cdn-go.cn
d.kugou.com
d2oarllo6tn86.cloudfront.net
frontier100-toutiao-lf.fqnovel.com
grpc.biliapi.net
log-auth.zztfly.com
logonext.tv.kuyun.com
m.ctrip.com
msch.f.360.cn
matomo.accesive.com
matomo.acmodasi.com
matomo.evl.fi
matomo.finance-in-motion.com
matomo.iolacorp.com
matomo.neugart.com
mbd.baidu.com
nbcollect.kugou.com
nbcollectretry.kugou.com
p2p.qq.com
pis-tel-pcdn.youku.com^
player-lg.youku.com^
rtlog5-applog-lf.fqnovel.com
sentry.5nix.com
sentry-old.northmill.com
sentry.northmill.com
ssgtm.rigtigkaffe.dk
sentry.ukr.net
sentry.dev.ukr.net
tp2p.kg.qq.com
tracking.unionen.se
tracking.filmtheaterbetriebe.de
twns.p2ptun.qq.com
vipauth.hpplay.cn
vipsdkauth.hpplay.cn
vv.play.aiseet.atianqi.com
volceapplog.com
yun-hl.3g.qq.com

这上面是一些广告跟踪器等等，这下面是我收集的一些主流软件的pcdn域名，是否要禁止你们考虑，而我是直接禁止的。
ws-p2p.pull.yximgs.com^
ws-p2p-pull.live-voip.com^
ws-p2p-v2.pull.yximgs.com^
ws-p2p-pull.video-voip.com^
qn-cdnfile1pcdn.msstatic.com^
pp-cdnfile1pcdn.msstatic.com^
qn-fileserverpcdn.cdn.huya.com^
xy-fileserverpcdn.cdn.huya.com^
xy-cdnfile1pcdn.msstatic.com^
xy-livewebbs2pcdn.msstatic.com^
qn-livewebbs2pcdn.msstatic.com^
fileserverpcdn.cdn.huya.com^
livewebbs2pcdn.msstatic.com^
tx-p2p.pull.yximgs.com^
tx-p2p-pull.video-voip.com^
tx-p2p-v2.pull.yximgs.com^
tx-p2p-pull.live-voip.com^
ali-bj-pcdn-11.biliapi.net^
qn-hydlpcdn.cdn.huya.com^
ks-p2p.pull.yximgs.com^
hw-p2p-v2.pull.yximgs.com^
hw-p2p-pull.video-voip.com^
hw-p2p.pull.yximgs.com^
hw-p2p-pull.live-voip.com^
ali-p2p.pull.yximgs.com^
ali-p2p-v2.pull.yximgs.com^
p2p-punch-v6.xxpkg.com

### 效果说明

你好，其实是这样的，你之前让我把域名整理一下发给你，我早就发过来，但是没有收到回复，然后发现我的GIthub账号被封禁了，原因未知，是否能解禁也不知道，然后我使用其它账号来回复。我的账号被封后，我的评论等等都变成404了，你是看不见的。如下面两张图所示，顺便说一下如果你想采纳这些域名就直接采纳，如果不想要就直接关闭，**不用回复我**，因为注册这个GitHub账号的邮箱是境外邮箱，需要使用vpn才能收到邮件，很麻烦，所以一般不用这个邮箱，也一般不用这个GitHub账号，因此你回复我也不知道。

![屏幕截图 2024-11-27 015921](https://github.com/user-attachments/assets/94cbb803-070c-4d4e-93dd-44d2462e01b4)
![屏幕截图 2024-11-27 020959](https://github.com/user-attachments/assets/6806e99b-4e80-4455-9f38-d940233a4c5f)

### 自查步骤

- [X] 我确认此拦截域名在本项目最新规则上并不存在，如因网络问题无法获取最新规则者还请自行解决
- [X] 我确认我已经搜索过 [Issue Tracker](https://github.com/TG-Twilight/AWAvenue-Ads-Rule/issues)，且并未查询到提交相同拦截域名的 Issue

**Comment by TG-Twilight** [comment]
@wudaodadi what？

**Comment by TG-Twilight** [comment]
还是一堆重复或根本不存在的域名。。。。。。
