### ISSUE TITLE
[enhancement] <提交拦截域名>提交拦截域名

### ISSUE THREAD

**Issue by mq00fc** [TG-Twilight/AWAvenue-Ads-Rule#106]
### 域名

# 百度
||ug.baidu.com^$important
||b.bdstatic.com^$important
||miao.baidu.com^$important
||s.bdstatic.com^$important
||hpd.baidu.com^$important
||ext.baidu.com^$important
||sp1.baidu.com^$important
||h2tcbox.baidu.com^$important
||mbdp02.bdstatic.com^$important

# CSDN
||eva2.csdn.net^
||ev.csdn.net^
||wkbrs1.tingyun.com^

# 小红书
||t2.xiaohongshu.com^
||fe.xiaohongshu.com^
||lng.xiaohongshu.com^
||apm-fe.xiaohongshu.com^
#||edith.xiaohongshu.com^

# bilibili
||data.bilibili.com^
||biligame.com^
||szbdyd.com^
||mcdn.bilivideo.cn^

# 知乎
||zhihu-web-analytics.zhihu.com^
||appcloud2.in.zhihu.com^
||mqtt.zhihu.com^
||sugar.zhihu.com^

# 抖音
||mssdk.bytedance.com^
||mon.zijieapi.com^
||mcs.zijieapi.com^
||bytegecko.com^
||bytegecko-i18n.com^
||bytedapm.com^

# Google
||google-analytics.com^
||googleads.g.doubleclick.net^
||pagead2.googlesyndication.com^
||csi.gstatic.com^

# 隐私保护
||public.api.nexon.com^
||static.doubleclick.net^
||ad.doubleclick.net^
||app-measurement.com^
||pixel-api.scupio.com^

# 腾讯
||tpstelemetry.tencent.com^
||h.trace.qq.com^

# 美团
||catfront.dianping.com^
||plx.meituan.com^

# 优酷
||ykad-data.youku.com^
||yk-ssp.ad.youku.com^
||pcapp-data-collect.youku.com^
||valipl.cp31.ott.cibntv.net^
||ynuf.aliapp.org^
||hudong.alicdn.com^
||acs.youku.com^

# 奈飞
||android-appboot.netflix.com^
||prod.cloud.netflix.com^
||appboot.netflix.com^

### 效果说明

日常使用抓到的域名，屏蔽后不会出现问题

### 自查步骤

- [X] 我确认此拦截域名在本项目最新规则上并不存在，如因网络问题无法获取最新规则者还请自行解决
- [X] 我确认我已经搜索过 [Issue Tracker](https://github.com/TG-Twilight/AWAvenue-Ads-Rule/issues)，且并未查询到提交相同拦截域名的 Issue

**Comment by TG-Twilight** [comment]
@mq00fc 感谢你的提交，在检查过后，我们会决定此域名是否添加进主规则中。

**Comment by TG-Twilight** [comment]
里面部分域名是正常域名，屏蔽后会影响功能。
