### ISSUE TITLE
[BUG] <问题标题>oauth-login-drcn.platform.dbankcloud.com

### ISSUE THREAD

**Issue by wudaodadi** [TG-Twilight/AWAvenue-Ads-Rule#108]
### 问题描述

oauth-login-drcn.platform.dbankcloud.com是华为账号登录用的域名，拦截这个域名会导致登录时异常，建议添加到白名单

### 自查步骤

- [X] 我确认我已经详细阅读过[使用教程](https://awavenue.top/Knowledge.html)，且此问题并未在其中得到解决
- [X] 我确认此问题是由本项目规则引起或与其相关，请勿提交与本项目无关 Issue
- [X] 我确认此问题在本项目最新规则上依然存在，如因网络问题无法获取最新规则者还请自行解决
- [X] 我确认我已经搜索过 [Issue Tracker](https://github.com/TG-Twilight/AWAvenue-Ads-Rule/issues)，且并未查询到类似内容
- [X] 我确认本 Issue 只提及一个问题，如有多个问题，烦请提交多个 Issue

**Comment by TG-Twilight** [comment]
@wudaodadi 经过实际测试，暂时没有发现会导致登录异常。

**Comment by wudaodadi** [comment]
> @wudaodadi 经过实际测试，暂时没有发现会导致登录异常。

是这样的，我在华为的电子邮件软件登录华为的花瓣邮箱时就出现异常，我要登录花瓣邮箱就要输入华为账号密码登录，然后就失败了，失败了三次，然后我查看Adguard的日志后发现这个域名，我记得是关于华为登录的，禁止后又能正常登录了。

我刚刚又去尝试了一下，没有成功复现。问题可能不是在这个域名，可能就是这个邮箱会偶然性登录不上
