### ISSUE TITLE
[BUG] 京东首页打不开

### ISSUE THREAD

**Issue by HolyGu** [TG-Twilight/AWAvenue-Ads-Rule#112]
### 问题描述

京东首页调用的JS地址被拦截导致京东首页无法加载

### 复现步骤

域名wl.jd.com被拦截，但是京东首页调用了https://wl.jd.com/wl.js
![image](https://github.com/user-attachments/assets/2e382787-8f07-4e08-a08d-c0be3e6dab75)
尝试放通此域名京东首页可正常加载
![image](https://github.com/user-attachments/assets/f4b79972-0272-45ad-80b9-584ecabf1f57)

### 自查步骤

- [X] 我确认我已经详细阅读过[使用教程](https://awavenue.top/Knowledge.html)，且此问题并未在其中得到解决
- [X] 我确认此问题是由本项目规则引起或与其相关，请勿提交与本项目无关 Issue
- [X] 我确认此问题在本项目最新规则上依然存在，如因网络问题无法获取最新规则者还请自行解决
- [X] 我确认我已经搜索过 [Issue Tracker](https://github.com/TG-Twilight/AWAvenue-Ads-Rule/issues)，且并未查询到类似内容
- [X] 我确认本 Issue 只提及一个问题，如有多个问题，烦请提交多个 Issue

**Comment by TG-Twilight** [comment]
@HolyGu 你好，感谢反馈。

我们会对此域名进行核查。

**Comment by TG-Twilight** [comment]
你好，经过简单的测试，确实是错误拦截的。

已经移除了这个域名，谢谢你的反馈！
