### ISSUE TITLE
[BUG] <问题标题>抖音登录账号时人脸识别加载失败。而导致无法登陆账号。

### ISSUE THREAD

**Issue by changzhaoCZ** [TG-Twilight/AWAvenue-Ads-Rule#113]
### 问题描述

拦截了saveu5-normal-lq.zijieapi.com导致抖音登录时人脸验证失败。

### 复现步骤

以上规则中的域名拦截。导致标题中出现的问题，手动加入白名单后恢复正常

### 问题截图

![IMG_20241226_222626](https://github.com/user-attachments/assets/6cf147a6-63a1-4ad6-b9b8-9507cb5fbb13)

### 自查步骤

- [X] 我确认我已经详细阅读过[使用教程](https://awavenue.top/Knowledge.html)，且此问题并未在其中得到解决
- [X] 我确认此问题是由本项目规则引起或与其相关，请勿提交与本项目无关 Issue
- [X] 我确认此问题在本项目最新规则上依然存在，如因网络问题无法获取最新规则者还请自行解决
- [X] 我确认我已经搜索过 [Issue Tracker](https://github.com/TG-Twilight/AWAvenue-Ads-Rule/issues)，且并未查询到类似内容
- [X] 我确认本 Issue 只提及一个问题，如有多个问题，烦请提交多个 Issue

**Comment by TG-Twilight** [comment]
好的，这个问题今晚会被解决，感谢反馈，久等了。

**Comment by TG-Twilight** [comment]
已经移除，感谢你的提交！
