### ISSUE TITLE
偶然看到的，不知道可不可以加入

### ISSUE THREAD

**Issue by Mubai-meng** [TG-Twilight/AWAvenue-Ads-Rule#22]
![Screenshot_2023-11-07-17-46-42-927_com.coolapk.market.jpg](https://github.com/TG-Twilight/AWAvenue-Adblock-Rule/assets/86759349/0e043c9d-9319-4205-9f88-516adb54161b)

**Comment by TG-Twilight** [comment]
有没有相关的页面? 我测试测试。

**Comment by Mubai-meng** [comment]
> 有没有相关的页面? 我测试测试。

丰巢公众号
但是我没找到具体的页面，估计是要有取件码才行

**Comment by TG-Twilight** [comment]
@Mubai-meng 好的

**Comment by TG-Twilight** [comment]
已经添加
