### ISSUE TITLE
希望添加hosts格式的支持

### ISSUE THREAD

**Issue by Sun020422** [TG-Twilight/AWAvenue-Ads-Rule#26]
本人正在使用大圣净化的hosts替换功能屏蔽广告，里面支持第三方订阅hosts源，请求作者增加hosts的格式支持

**Comment by TG-Twilight** [comment]
我看看大圣用的hosts规则大概长什么样？然后空了再写文件

**Comment by TG-Twilight** [comment]
你写个markdown

**Comment by Sun020422** [comment]
抱歉，我不太理解您让我写markdown的意思，但是我给您发一个hosts示李
https://gitlab.com/jdlingyu/ext_rules/raw/main/hosts/hosts

**Comment by TG-Twilight** [comment]
@Sun020422 好，大概知道了，不出意外下周支持

**Comment by Sun020422** [comment]
十分感谢

**Comment by TG-Twilight** [comment]
已经添加。
