### ISSUE TITLE
可以出个DNS规则？

### ISSUE THREAD

**Issue by biange200** [TG-Twilight/AWAvenue-Ads-Rule#27]
就是可以支持personaldnsfilter invizible pro
这些DNS去广告软件的 domains wildcard规则？

**Comment by TG-Twilight** [comment]
@biange200 给一个规则示例

**Comment by biange200** [comment]
> @biange200 给一个规则示例

https://small.oisd.nl/domainswild

https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/light-onlydomains.txt

![Screenshot_20231228_214606.jpg](https://github.com/TG-Twilight/AWAvenue-Ads-Rule/assets/37582806/4ae040d5-d89c-431b-a3ad-645be0542b67)

**Comment by TG-Twilight** [comment]
自己多看

**Comment by biange200** [comment]
> 自己多看

adblock语法的在invizible pro personaldnsfilter上用不了
所以我才问你可以增加其他语法规则？

**Comment by TG-Twilight** [comment]
AdClose的规则

**Comment by biange200** [comment]
> AdClose的规则，没问题了就吭个声

手机上没安装adguard APP
火狐浏览器插件可以用你规则
不过我手机上用的是rethinkdns blokada pdnsf这些软件，不支持adblock语法规则

**Comment by biange200** [comment]
> try use https://github.com/TG-Twilight/AWAvenue-Ads-Rule/blob/main/Filters/AWAvenue-Ads-Rule-hosts

好的

**Comment by lalasou** [comment]
能不能加个smartdns版本   谢谢
👍

**Comment by biange200** [comment]
> 能不能加个smartdns版本   谢谢
> 👍

我不是作者，你发错了

**Comment by lalasou** [comment]
```
curl -sL -o ad.conf https://ghproxy.net/https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main/Filters/AWAvenue-Ads-Rule-hosts.txt && sed -i '1,20d;s/^127\.0\.0\.1\s\+\(.*\)/address \/\1\/#/g' ad.conf
```
去掉前20是因为菜 不方便替换操作

**Comment by TG-Twilight** [comment]
如果需要提issue请新开一个而不是在已经关闭的issue中提。
