### ISSUE TITLE
hosts文件问题及建议

### ISSUE THREAD

**Issue by bian2022** [TG-Twilight/AWAvenue-Ads-Rule#29]
在300行左右有个是
mp.weixin.qq.com/mp/getappmsgad
hosts应该只是域名吧
另外希望把数量精简到100个？
原因：阿里云现在提供的公共DNS黑名单只支持100个域名（但添加的时候可以一起包括子域名）

**Comment by bian2022** [comment]
还有第三百七十行左右
service.vmos.cn/vmospro/api/ad

**Comment by TG-Twilight** [comment]
@bian2022 你可以用AdGuard DNS

**Comment by bian2022** [comment]
> @bian2022 你可以用AdGuard DNS

现在就是用的这个，但是延迟高

**Comment by TG-Twilight** [comment]
@bian2022 那请自便，自己动手
