### ISSUE TITLE
[BUG] <错误拦截xbox域名>

### ISSUE THREAD

**Issue by blueberry-pie-11** [TG-Twilight/AWAvenue-Ads-Rule#31]
### 问题描述

拦截 catalog.gamepass.com 导致xbox应用无法获取游戏列表，包括商店游戏列表和库存列表等

### 自查步骤

- [X] 我确认我已经详细阅读过[使用教程](https://awavenue.top/Knowledge.html)，且此问题并未在其中得到解决
- [X] 我确认此问题是由本项目规则引起或与其相关，请勿提交与本项目无关 Issue
- [X] 我确认此问题在本项目最新规则上依然存在，如因网络问题无法获取最新规则者还请自行解决
- [X] 我确认我已经搜索过 [Issue Tracker](https://github.com/TG-Twilight/AWAvenue-Ads-Rule/issues)，且并未查询到类似内容
- [X] 我确认本 Issue 只提及一个问题，如有多个问题，烦请提交多个 Issue

**Comment by TG-Twilight** [comment]
已经修复
