### ISSUE TITLE
[建议] 小提议（非bug）

### ISSUE THREAD

**Issue by echs-top** [TG-Twilight/AWAvenue-Ads-Rule#32]
### 问题描述

可以使用vercel反代一个github仓库帮来增加一个订阅链接，vercel可以自动同步部署github仓库，不过需要自己准备一个域名

### 复现步骤

可以使用vercel反代一个github仓库帮来增加一个订阅链接，vercel可以自动同步部署github仓库，不过需要自己准备一个域名

### 自查步骤

- [X] 我确认我已经详细阅读过[使用教程](https://awavenue.top/Knowledge.html)，且此问题并未在其中得到解决
- [X] 我确认此问题是由本项目规则引起或与其相关，请勿提交与本项目无关 Issue
- [X] 我确认此问题在本项目最新规则上依然存在，如因网络问题无法获取最新规则者还请自行解决
- [X] 我确认我已经搜索过 [Issue Tracker](https://github.com/TG-Twilight/AWAvenue-Ads-Rule/issues)，且并未查询到类似内容
- [X] 我确认本 Issue 只提及一个问题，如有多个问题，烦请提交多个 Issue

**Comment by TG-Twilight** [comment]
@echs-top 不是有那么多个反代链接吗

**Comment by heinu123** [comment]
没必要用vercel，有jsd cdn和jsd国内镜像并且vercel还会跳反诈
