### ISSUE TITLE
[BUG] <误杀花瓣测速>

### ISSUE THREAD

**Issue by xunpod** [TG-Twilight/AWAvenue-Ads-Rule#34]
### 问题描述

拦截h5hosting.dbankcdn.com导致花瓣测速无法获取测速服务器列表

### 自查步骤

- [X] 我确认我已经详细阅读过[使用教程](https://awavenue.top/Knowledge.html)，且此问题并未在其中得到解决
- [X] 我确认此问题是由本项目规则引起或与其相关，请勿提交与本项目无关 Issue
- [X] 我确认此问题在本项目最新规则上依然存在，如因网络问题无法获取最新规则者还请自行解决
- [X] 我确认我已经搜索过 [Issue Tracker](https://github.com/TG-Twilight/AWAvenue-Ads-Rule/issues)，且并未查询到类似内容
- [X] 我确认本 Issue 只提及一个问题，如有多个问题，烦请提交多个 Issue

**Comment by heinu123** [comment]
提供一下截图

**Comment by xunpod** [comment]
该问题已在几小时前修复，为复现此问题，重新复原此前拦截的规则
![adguard拦截日志](https://github.com/TG-Twilight/AWAvenue-Ads-Rule/assets/91523109/b5b224d3-7f03-4a9e-8cd6-1fe839794d42)
![花瓣测速app界面](https://github.com/TG-Twilight/AWAvenue-Ads-Rule/assets/91523109/e43fbf51-1c57-47ef-a4de-d5a6052cf596)
