### ISSUE TITLE
[BUG] <华为运动健康app图片资源>

### ISSUE THREAD

**Issue by LittleJake** [TG-Twilight/AWAvenue-Ads-Rule#35]
### 问题描述

拦截contentcenter-drcn.dbankcdn.cn，导致华为运动健康图片资源无法加载。

### 复现步骤

Stream抓包发现，AdGuardHome测试域名确认为拦截。

### 自查步骤

- [X] 我确认我已经详细阅读过[使用教程](https://awavenue.top/Knowledge.html)，且此问题并未在其中得到解决
- [X] 我确认此问题是由本项目规则引起或与其相关，请勿提交与本项目无关 Issue
- [X] 我确认此问题在本项目最新规则上依然存在，如因网络问题无法获取最新规则者还请自行解决
- [X] 我确认我已经搜索过 [Issue Tracker](https://github.com/TG-Twilight/AWAvenue-Ads-Rule/issues)，且并未查询到类似内容
- [X] 我确认本 Issue 只提及一个问题，如有多个问题，烦请提交多个 Issue

**Comment by TG-Twilight** [comment]
截个图瞅瞅

**Comment by LittleJake** [comment]
![0](https://github.com/TG-Twilight/AWAvenue-Ads-Rule/assets/13583702/58c5c741-3e65-4e70-900f-ef6fac69771c)
![9](https://github.com/TG-Twilight/AWAvenue-Ads-Rule/assets/13583702/44a4464e-84bc-4c92-9719-300b126c31a3)
![384](https://github.com/TG-Twilight/AWAvenue-Ads-Rule/assets/13583702/b0e7caf9-7cc2-4dad-8729-1f3e026bf5f5)

**Comment by TG-Twilight** [comment]
行，之前拦截这些是为了拦截你家天气的开屏广告

**Comment by LittleJake** [comment]
> 行，之前拦截这些是为了拦截你家天气的开屏广告，之后此域名会移动到补充规则里。

不过这些玩意确实挺恶心人的，不同业务都放在同一个域名🤮
