### ISSUE TITLE
[BUG] 误杀抖音APP申报学校信息功能

### ISSUE THREAD

**Issue by xunpod** [TG-Twilight/AWAvenue-Ads-Rule#36]
### 问题描述

规则`/i*.snssdk.com/`拦截`aweme.snssdk.com`导致抖音APP的填写学校->学校信息->申报学校信息异常

### 问题截图

![拦截日志](https://github.com/TG-Twilight/AWAvenue-Ads-Rule/assets/91523109/95e8ed8d-bef8-4fbb-9c12-404b515d6620)
![错误界面](https://github.com/TG-Twilight/AWAvenue-Ads-Rule/assets/91523109/19be76b2-44ee-4681-ad14-aa5e033ac162)

### 自查步骤

- [X] 我确认我已经详细阅读过[使用教程](https://awavenue.top/Knowledge.html)，且此问题并未在其中得到解决
- [X] 我确认此问题是由本项目规则引起或与其相关，请勿提交与本项目无关 Issue
- [X] 我确认此问题在本项目最新规则上依然存在，如因网络问题无法获取最新规则者还请自行解决
- [X] 我确认我已经搜索过 [Issue Tracker](https://github.com/TG-Twilight/AWAvenue-Ads-Rule/issues)，且并未查询到类似内容
- [X] 我确认本 Issue 只提及一个问题，如有多个问题，烦请提交多个 Issue

**Comment by TG-Twilight** [comment]
已修复。
