### ISSUE TITLE
[BUG] <小米云备份异常>

### ISSUE THREAD

**Issue by blueberry-pie-11** [TG-Twilight/AWAvenue-Ads-Rule#38]
### 问题描述

拦截 a0.app.xiaomi.com 导致小米云备份异常。一般情况下，该域名用于上传应用安装列表，从而实现部分人遇见过的404打电话通知不要安装诈骗app。但拦截后，小米云备份无法上传应用列表完成备份。
建议酌情处理

### 自查步骤

- [x] 我确认我已经详细阅读过[使用教程](https://awavenue.top/Knowledge.html)，且此问题并未在其中得到解决
- [X] 我确认此问题是由本项目规则引起或与其相关，请勿提交与本项目无关 Issue
- [X] 我确认此问题在本项目最新规则上依然存在，如因网络问题无法获取最新规则者还请自行解决
- [X] 我确认我已经搜索过 [Issue Tracker](https://github.com/TG-Twilight/AWAvenue-Ads-Rule/issues)，且并未查询到类似内容
- [X] 我确认本 Issue 只提及一个问题，如有多个问题，烦请提交多个 Issue

**Comment by TG-Twilight** [comment]
@blueberry-pie-11 建议你使用Swiftbackup，支持备份apk的同时可以备份应用数据。

而不是miui的应用备份。

这个 a0.app.xiaomi.com 会继续存在于主规则里，如果你非用不可建议自行手动注释或者使用时关闭拦截工具。

**Comment by TG-Twilight** [comment]
@blueberry-pie-11 We believe that protecting your privacy is more important than convenience.

In particular, it is absolutely unacceptable to be uploaded private data without your knowledge and permission, or even be asked to uninstall the app.
