### ISSUE TITLE
搜狗输入法跨屏输入的网页被拦截

### ISSUE THREAD

**Issue by changzhaoCZ** [TG-Twilight/AWAvenue-Ads-Rule#45]
### 问题描述

拦截shouji.sougou.com导致手机扫描电视版搜狗输入法二维码而打不开跨屏输入页面

### 复现步骤

在大圣净化中启用host规则，重启手机，扫描当贝盒子上自带的搜狗输入法tv版二维码，浏览器无法打开跨屏输入页面

### 自查步骤

- [X] 我确认我已经详细阅读过[使用教程](https://awavenue.top/Knowledge.html)，且此问题并未在其中得到解决
- [X] 我确认此问题是由本项目规则引起或与其相关，请勿提交与本项目无关 Issue
- [X] 我确认此问题在本项目最新规则上依然存在，如因网络问题无法获取最新规则者还请自行解决
- [X] 我确认我已经搜索过 [Issue Tracker](https://github.com/TG-Twilight/AWAvenue-Ads-Rule/issues)，且并未查询到类似内容
- [X] 我确认本 Issue 只提及一个问题，如有多个问题，烦请提交多个 Issue

**Comment by changzhaoCZ** [comment]
https://www.123pan.com/s/rox9-pHdQh.html
我分享了该搜狗输入法版本，可安装后复现该问题

**Comment by heinu123** [comment]
直接提供拦截日志，而不是搜狗输入法版本

**Comment by TG-Twilight** [comment]
请问问题得到了解决吗？我们已经移除了相关的域名。

**Comment by changzhaoCZ** [comment]
抱歉，我输错了域名，不是shouji.sougou.com    而是shouji.sogou.com
刚才我查看了最新的host规则，即https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main/Filters/AWAvenue-Ads-Rule-hosts.txt
发现导致错误的host的规则依旧存在。
此规则为 127.0.0.1 shouji.sogou.com
输入host文件后重启，该问题复现。
移除相关规则后，重启手机，问题解决。

**Comment by TG-Twilight** [comment]
@changzhaoCZ 好的，马上修，这会大脑有点宕机😂

**Comment by heinu123** [comment]
但是，此域名用途是收集用户输入习惯 甚至输入文字 共享到其它APP(广告推送)

**Comment by heinu123** [comment]
但是，此域名用途是收集用户输入习惯 甚至输入文字 共享到其它APP(广告推送)

**Comment by TG-Twilight** [comment]
我们讨论了一下，别的维护者告诉我这条域名会上传用户的输入习惯和输入的文字，处于对您隐私的保护，经过讨论后，我们认为这条域名应该被屏蔽而不是被放行，如果您有需要，请单独放行，稍后我们会完善本项目的README文件，对进入主规则但可能会拦截一些服务的条目进行说明，非常感谢您的积极反馈！

**Comment by changzhaoCZ** [comment]
好的

**Comment by TG-Twilight** [comment]
如果没有别的问题，此issue将会在2024年3月17日0时(UTC+8)关闭，在此之前，您亦可选择主动关闭。
