### ISSUE TITLE
[申请授权] anti-AD项目申请引用贵项目的广告列表

### ISSUE THREAD

**Issue by gentlyxu** [TG-Twilight/AWAvenue-Ads-Rule#46]
### 域名

非常冒昧，无法提出一个符合项目要求格式的一个issue。

首先自我介绍：

> anti-AD是致力于成为中文区命中率最高的广告过滤列表，实现精确的广告屏蔽和隐私保护。anti-AD现已支持AdGuardHome，dnsmasq， Surge，Pi-Hole，smartdns等网络组件。完全兼容常见的广告过滤工具所支持的各种广告过滤列表格式
使用anti-AD能够屏蔽广告域名，能屏蔽电视盒子广告，屏蔽app内置广告，同时屏蔽了一些日志收集、大数据统计等涉及个人隐私信息的站点，能够保护个人隐私不被偷偷上传。
>
>本工具是通过域名解析层来屏蔽广告和保护隐私的，其将各大著名的hosts，ad filter lists，adblock list等的列表进行合并去重，再进行一系列的抽象化，例如主动剔除失效域名、easylist优化模糊匹配、增强的黑白名单机制等措施，最终生成期望的高命中率列表。

anti-AD目前是MIT license，一直是一个非盈利、非商业项目。

我们有朋友在项目的issue中提出[希望anti-AD能引用《AWAvenue 秋风广告规则》](https://github.com/privacy-protection-tools/anti-AD/issues/897)，经过实地考察，发现你们是一个非常优秀、极具活力的项目，我们有着共同的“帮助用户拦截广告、保护隐私”的目标，希望能引用你们的主列表，帮助anti-AD获得更强的拦截能力

在此向你们申请获得引用授权

### 效果说明

无

### 自查步骤

- [x] 我确认此拦截域名在本项目最新规则上并不存在，如因网络问题无法获取最新规则者还请自行解决
- [X] 我确认我已经搜索过 [Issue Tracker](https://github.com/TG-Twilight/AWAvenue-Ads-Rule/issues)，且并未查询到提交相同拦截域名的 Issue

**Comment by TG-Twilight** [comment]
可以，但我们希望你们在anti的仓库和网站中为我们的项目增加一个显眼的推荐，即“如果您有最小体积的广告拦截列表之需求（例如在OpenWrt系统上添加广告拦截列表），则建议您使用秋风广告规则”，您看如何？

我们最近也正在修改本项目的README，之后新的README大概意思也会是如此。

**Comment by TG-Twilight** [comment]
如果您可以接受，我们则非常欢迎anti-AD与秋风广告规则(AWAvenue Ads Rule)一同携手共进，期待您的回复。

**Comment by TG-Twilight** [comment]
好的，你可以按照你的方式进行引用感谢，但恕我冒昧地问一下，我想知道anti的官方网站是否也应该罗列出引用感谢呢？

就像 https://awavenue.top/Thank.html 之类的。
