### ISSUE TITLE
[enhancement] <提交拦截域名>

### ISSUE THREAD

**Issue by merrkry** [TG-Twilight/AWAvenue-Ads-Rule#47]
### 域名

`grs.platform.dbankcloud.ru`

### 效果说明

在我的环境中，HMS Core 会不断请求该域名，造成严重的资源浪费。

- 这大概率是一个广告或跟踪器域名：[1Hosts 在其主列表收录了此域名](https://github.com/badmojr/1Hosts/issues/103)。
- 预计屏蔽后不会对正常使用造成影响：公共 DNS 查询不到相关的解析结果。推测是连接不上其他 `dbankcloud` 时的后备选项，且只能通过 httpdns 解析，或根本没有实际启用。

### 自查步骤

- [x] 我确认此拦截域名在本项目最新规则上并不存在，如因网络问题无法获取最新规则者还请自行解决
- [X] 我确认我已经搜索过 [Issue Tracker](https://github.com/TG-Twilight/AWAvenue-Ads-Rule/issues)，且并未查询到提交相同拦截域名的 Issue

**Comment by TG-Twilight** [comment]
@merrkry 好的，我会对该域名进行二次检查，之后会决定是否添加进广告规则里，若收录，感谢你的反馈！

**Comment by merrkry** [comment]
补充：又发现了一个域名，`appcloud2.in.zhihu.com`，也是类似情况

- 没有公网解析结果
- APP 会以暴力重试，不断查询
- 在 [其他类似项目](https://raw.githubusercontent.com/zqzess/rule_for_quantumultX/master/Surge/Module/zhihu.sgmodule) 被标记为需要屏蔽。

**Comment by TG-Twilight** [comment]
@merrkry 好的，谢谢你的提交，这些域名在经过检查后最晚会在明天被添加进规则，届时的更新日志会有相应的感谢文字。

**Comment by TG-Twilight** [comment]
已经添加，感谢会在发更新日志时列出。
