### ISSUE TITLE
能否增加 RouterOS 的适配规则？

### ISSUE THREAD

**Issue by kiss2u** [TG-Twilight/AWAvenue-Ads-Rule#49]
### 域名

RouterOS 适配文件后缀是 .rsc，类似于这样的：https://cdn.jsdelivr.net/gh/neoFelhz/neohosts@gh-pages/basic/mikrotik.rsc
秋风规则很精简，非常适合 RouterOS 这种性能不强的路由系统去广告，望大佬采纳。

### 效果说明

秋风规则很精简，非常适合 RouterOS 这种性能不强的路由系统去广告，望大佬采纳。

### 自查步骤

- [X] 我确认此拦截域名在本项目最新规则上并不存在，如因网络问题无法获取最新规则者还请自行解决
- [X] 我确认我已经搜索过 [Issue Tracker](https://github.com/TG-Twilight/AWAvenue-Ads-Rule/issues)，且并未查询到提交相同拦截域名的 Issue

**Comment by kiss2u** [comment]
此外，我做了shell，可以自动处理，将hosts模式转换为 rsc 文件，共参考：

`#!/bin/bash

# 从下载网站中下载去广告文件
websites=(
  "https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main/Filters/AWAvenue-Ads-Rule-hosts.txt"
  "https://jsd.onmicrosoft.cn/gh/TG-Twilight/AWAvenue-Ads-Rule@main/Filters/AWAvenue-Ads-Rule-hosts.txt"
  "https://gcore.jsdelivr.net/gh/TG-Twilight/AWAvenue-Ads-Rule@main/Filters/AWAvenue-Ads-Rule-hosts.txt"
  "https://mirror.ghproxy.com/https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main/Filters/AWAvenue-Ads-Rule-hosts.txt"
)

# 循环测试网站，直到成功下载 ad.txt 文件
for website in "${websites[@]}"; do
  echo "正在尝试从 $website 下载 ad.txt 文件..."
  curl -sL "$website" -o "ad.txt"
  if [ $? -eq 0 ]; then
    echo "下载 ad.txt 文件成功！"
    break
  else
    echo "下载 ad.txt 文件失败，请重试..."
  fi
done

# 判断是否成功下载 ad.txt 文件
if [ ! -f "ad.txt" ]; then
  echo "无法从网站中获取球风脚本，请重试..."
  exit 1
fi

# 处理 ad.txt 文件
echo "正在处理 ad.txt 文件..."
sed -i '/localhost/d' "ad.txt"
sed -i 's/127.0.0.1 /ip dns static add address=240.0.0.1 name=/g' "ad.txt"

# 将 ad.txt 改名为 ad.rsc
mv ad.txt ad.rsc

# 提示成功信息
echo "广告脚本处理成功！"
`

**Comment by heinu123** [comment]
查阅 https://github.com/TG-Twilight/AWAvenue-Ads-Rule/tree/build/script 的readme
你可以写一份RouterOS的转换插件然后pr 语言为Python

**Comment by kiss2u** [comment]
> 查阅 https://github.com/TG-Twilight/AWAvenue-Ads-Rule/tree/build/script 的readme 你可以写一份RouterOS的转换插件然后pr 语言为Python

已发 PR

https://github.com/TG-Twilight/AWAvenue-Ads-Rule/pull/51

**Comment by TG-Twilight** [comment]
之后相关的订阅会在我们的[官方网站](https://awavenue.top/Sub.html)更新，当然，你也可以直接pr我们的[官方网站项目](https://github.com/AWAvenue/AWAvenueAdsWebSite)。
