### ISSUE TITLE
[BUG] <发现一个错误>

### ISSUE THREAD

**Issue by LLSS00001111** [TG-Twilight/AWAvenue-Ads-Rule#53]
### 问题描述

错误：api-access.pangolin-sdk-toutiao.com3

正确：api-access.pangolin-sdk-toutiao.com

建议删除 api-access.pangolin-sdk-toutiao.com3

规则已有 api-access.pangolin-sdk-toutiao.com

### 复现步骤

任意规则查找 api-access.pangolin-sdk-toutiao.com3

### 问题截图

AdGuard Home/DNS

![IMG_0122](https://github.com/TG-Twilight/AWAvenue-Ads-Rule/assets/164380557/0e1f68d2-be70-4417-b665-391f37db78f3)

hosts

![IMG_0123](https://github.com/TG-Twilight/AWAvenue-Ads-Rule/assets/164380557/96f07264-8d5a-49c4-9d5d-b5206aab5f9d)

蓝猫

![IMG_0125](https://github.com/TG-Twilight/AWAvenue-Ads-Rule/assets/164380557/784f5eca-8ce7-47b1-97c8-b0a68c63af53)

Surge/Surfboard

![IMG_0124](https://github.com/TG-Twilight/AWAvenue-Ads-Rule/assets/164380557/2d3ae0e2-2ad7-428f-8e60-c1bf69e6c78c)

### 自查步骤

- [X] 我确认我已经详细阅读过[使用教程](https://awavenue.top/Knowledge.html)，且此问题并未在其中得到解决
- [X] 我确认此问题是由本项目规则引起或与其相关，请勿提交与本项目无关 Issue
- [X] 我确认此问题在本项目最新规则上依然存在，如因网络问题无法获取最新规则者还请自行解决
- [X] 我确认我已经搜索过 [Issue Tracker](https://github.com/TG-Twilight/AWAvenue-Ads-Rule/issues)，且并未查询到类似内容
- [X] 我确认本 Issue 只提及一个问题，如有多个问题，烦请提交多个 Issue

**Comment by TG-Twilight** [comment]
@LLSS00001111 好的，感谢反馈
