### ISSUE TITLE
能否支持mosdns v5的广告拦截规则

### ISSUE THREAD

**Issue by hanxin1997** [TG-Twilight/AWAvenue-Ads-Rule#54]
### 域名

mosdns仓库：https://github.com/IrineSistiana/mosdns
mosdns拦截规则的参考格式：https://gp.adrules.top/mosdns_adrules.txt

### 效果说明

AWAvenue-Ads-Rule是一款十分优秀的去广告规则，很精简十分合适用在广泛用于软路由dns分流的mosdns上，但是苦于没有标准规则。

### 自查步骤

- [X] 我确认此拦截域名在本项目最新规则上并不存在，如因网络问题无法获取最新规则者还请自行解决
- [X] 我确认我已经搜索过 [Issue Tracker](https://github.com/TG-Twilight/AWAvenue-Ads-Rule/issues)，且并未查询到提交相同拦截域名的 Issue

**Comment by TG-Twilight** [comment]
好的，近期维护者们都比较忙，过一段时间此格式的规则将会受到支持。当然，向我们提供Pr我们也是乐意的。

**Comment by luzhaohui** [comment]
> 好的，近期维护者们都比较忙，过一段时间此格式的规则将会受到支持。当然，向我们提供Pr我们也是乐意的。

确有需求，目前局域网中用 MosDNS 的不在少数，尤其是需要进行国内外DNS分流的用户，基本都在使用 MosDNS。
所以，有空了，还望可以专门针对 MosDNS v5 进行数据格式化。谢谢

**Comment by TG-Twilight** [comment]
已经添加了对于Mosdns_v5的支持，现在，你可以使用它了。


反代订阅链接和官网的更新指南会有延迟。
