### ISSUE TITLE
拦截qq安全中心的验证码同步地址

### ISSUE THREAD

**Issue by lzqd** [TG-Twilight/AWAvenue-Ads-Rule#57]
### 问题描述

拦截qq安全中心的验证码以及安全信息等相关获取地址
tdid.m.qq.com

### 复现步骤

放行tdid.m.qq.com后QQ安全中心验证码同步以及安全信息等相关正常获取

### 自查步骤

- [X] 我确认我已经详细阅读过[使用教程](https://awavenue.top/Knowledge.html)，且此问题并未在其中得到解决
- [X] 我确认此问题是由本项目规则引起或与其相关，请勿提交与本项目无关 Issue
- [X] 我确认此问题在本项目最新规则上依然存在，如因网络问题无法获取最新规则者还请自行解决
- [X] 我确认我已经搜索过 [Issue Tracker](https://github.com/TG-Twilight/AWAvenue-Ads-Rule/issues)，且并未查询到类似内容
- [X] 我确认本 Issue 只提及一个问题，如有多个问题，烦请提交多个 Issue

**Comment by TG-Twilight** [comment]
@lzqd 好的，晚些时间我们会修复此问题
