### ISSUE TITLE
[Improve] 列表中存在重复/多余的规则

### ISSUE THREAD

**Issue by MkQtS** [TG-Twilight/AWAvenue-Ads-Rule#64]
### 问题描述

例如下面4条只需要最后一条就行了

```adblock
||ad.flurry.com^
||adlog.flurry.com^
||ads.flurry.com^
||flurry.com^
```

可以使用此工具 https://adblockplus.org/zh_CN/redundancy_check 检查

### 自查步骤

- [X] 我确认我已经详细阅读过[使用教程](https://awavenue.top/Knowledge.html)，且此问题并未在其中得到解决
- [X] 我确认此问题是由本项目规则引起或与其相关，请勿提交与本项目无关 Issue
- [X] 我确认此问题在本项目最新规则上依然存在，如因网络问题无法获取最新规则者还请自行解决
- [X] 我确认我已经搜索过 [Issue Tracker](https://github.com/TG-Twilight/AWAvenue-Ads-Rule/issues)，且并未查询到类似内容
- [X] 我确认本 Issue 只提及一个问题，如有多个问题，烦请提交多个 Issue

**Comment by TG-Twilight** [comment]
好的，十分感谢你的提醒！这个问题今天会解决。
