### ISSUE TITLE
喵趣漫画app误拦

### ISSUE THREAD

**Issue by vcdriy** [TG-Twilight/AWAvenue-Ads-Rule#65]
### 问题描述

拦截panglelog.gz.bcebos.com会导致漫画无法加载，加入白名单会有个开屏，但不是广告。

### 问题截图

![Screenshot_2024-05-02-13-03-26-94_3ebb194ba85cb8063cae7973d9fdc4e1](https://github.com/TG-Twilight/AWAvenue-Ads-Rule/assets/140751279/832dadda-08d9-47d5-8a0c-654e047b1e06)
![Screenshot_2024-05-02-13-02-58-42_3ebb194ba85cb8063cae7973d9fdc4e1](https://github.com/TG-Twilight/AWAvenue-Ads-Rule/assets/140751279/e1971685-b6ec-45b7-ab40-c32aa0142b67)

### 自查步骤

- [X] 我确认我已经详细阅读过[使用教程](https://awavenue.top/Knowledge.html)，且此问题并未在其中得到解决
- [X] 我确认此问题是由本项目规则引起或与其相关，请勿提交与本项目无关 Issue
- [X] 我确认此问题在本项目最新规则上依然存在，如因网络问题无法获取最新规则者还请自行解决
- [X] 我确认我已经搜索过 [Issue Tracker](https://github.com/TG-Twilight/AWAvenue-Ads-Rule/issues)，且并未查询到类似内容
- [X] 我确认本 Issue 只提及一个问题，如有多个问题，烦请提交多个 Issue

**Comment by TG-Twilight** [comment]
@vcdriy 请截图看看

**Comment by TG-Twilight** [comment]
好的，今天会处理
