### ISSUE TITLE
[BUG] 华为手机预装天气app内更多天气页面无法加载

### ISSUE THREAD

**Issue by Rbqwow** [TG-Twilight/AWAvenue-Ads-Rule#66]
### 问题描述

如题 点开更多天气会启动一个webview加载网页
经排查是因为拦截了`weather-drcn.music.dbankcloud.cn`这个域名

话说这个域名本意拦截的是...?

### 自查步骤

- [X] 我确认我已经详细阅读过[使用教程](https://awavenue.top/Knowledge.html)，且此问题并未在其中得到解决
- [X] 我确认此问题是由本项目规则引起或与其相关，请勿提交与本项目无关 Issue
- [X] 我确认此问题在本项目最新规则上依然存在，如因网络问题无法获取最新规则者还请自行解决
- [X] 我确认我已经搜索过 [Issue Tracker](https://github.com/TG-Twilight/AWAvenue-Ads-Rule/issues)，且并未查询到类似内容
- [X] 我确认本 Issue 只提及一个问题，如有多个问题，烦请提交多个 Issue

**Comment by TG-Twilight** [comment]
weather-drcn.music.dbankcloud.cn

我是抓包拦截华为天气的开屏，把这个拦截了天气才没开屏了......

**Comment by Rbqwow** [comment]
又测了一下 更多天气加载失败确实是因为这个 但是没多出来开屏广告 奇奇怪怪
~~或许可以改到激进规则里？~~

**Comment by TG-Twilight** [comment]
@Rbqwow 我想请问一下拦截这个域名对你有什么影响吗？

**Comment by Rbqwow** [comment]
> @Rbqwow 我想请问一下拦截这个域名对正常使用有什么影响吗？

https://github.com/TG-Twilight/AWAvenue-Ads-Rule/assets/55343783/70bdf3b0-4195-4dd3-b6d0-9c4ecdcda982

像这样 拦截了这个域名 视频中这些都无法加载

**Comment by TG-Twilight** [comment]
好的，稍后会将这条域名移至补充规则
