### ISSUE TITLE
[enhancement] 噼哩噼哩mcdn屏蔽

### ISSUE THREAD

**Issue by PlutoNameless** [TG-Twilight/AWAvenue-Ads-Rule#68]
### 域名

```
*.mcdn.bilivideo.cn
```

### 效果说明

可直接使用
```
||mcdn.bilivideo.cn^
```
进行屏蔽，或屏蔽改域名下的三级及以上域名；
该网站在App、Web上使用pcdn分发作品中视频、音频流；
访问该网站调用pcdn分发的内容时，如果恰好使用的改pcdn节点满载将会出现该视频卡顿、加载缓慢情况；
屏蔽该域名后，将使用平台自建第一方cdn提供服务，且不会影响该平台提供的服务。

### 效果截图

在Web上，播放器右键点击「视频统计信息」可查看作品分发的cdn地址；
使用`*.mcdn.bilivideo.cn`域名的则当前访问的内容来自pcdn；
使用`*.bilivideo.cn`域名的则当前访问内容来自第一方cdn；

### 自查步骤

- [X] 我确认此拦截域名在本项目最新规则上并不存在，如因网络问题无法获取最新规则者还请自行解决
- [X] 我确认我已经搜索过 [Issue Tracker](https://github.com/TG-Twilight/AWAvenue-Ads-Rule/issues)，且并未查询到提交相同拦截域名的 Issue

**Comment by TG-Twilight** [comment]
done
