### ISSUE TITLE
[BUG] 哔哩哔哩App用户空间-商品-页面无法加载

### ISSUE THREAD

**Issue by PlutoNameless** [TG-Twilight/AWAvenue-Ads-Rule#70]
### 问题描述

![image](https://github.com/TG-Twilight/AWAvenue-Ads-Rule/assets/5725831/68774924-9dcc-455c-a666-ccbcee3272bf)
该规则导致App上，用户空间中商品选项卡内容无法加载

### 复现步骤

iOS Bilibili App 7.77.0
在拥有商品选项卡的用户空间页面，此规则导致该页面无法加载；
App拥有DNS缓存，当放行一次后，再加载此页面不会请求DNS

### 问题截图

手动放行过一次后无法复现错误页面；
并不是所有用户都拥有「商品」页面，同时测试发现，工坊请求的域名也为该域名。

### 自查步骤

- [X] 我确认我已经详细阅读过[使用教程](https://awavenue.top/Knowledge.html)，且此问题并未在其中得到解决
- [X] 我确认此问题是由本项目规则引起或与其相关，请勿提交与本项目无关 Issue
- [X] 我确认此问题在本项目最新规则上依然存在，如因网络问题无法获取最新规则者还请自行解决
- [X] 我确认我已经搜索过 [Issue Tracker](https://github.com/TG-Twilight/AWAvenue-Ads-Rule/issues)，且并未查询到类似内容
- [X] 我确认本 Issue 只提及一个问题，如有多个问题，烦请提交多个 Issue

**Comment by TG-Twilight** [comment]
@PlutoNameless 行，睡醒了看看
