### ISSUE TITLE
[BUG] <IP-CIDR 部分格式错误>

### ISSUE THREAD

**Issue by xiecang** [TG-Twilight/AWAvenue-Ads-Rule#71]
### 问题描述

> [ipcidr](https://wiki.metacubex.one/config/dns/#ipcidr)(https://wiki.metacubex.one/config/dns/#ipcidr)
>
> 书写内容为 IP/掩码

有两条格式不正确，导致转换后的规则 Clash Meta For Android 无法正确解析
https://github.com/TG-Twilight/AWAvenue-Ads-Rule/blob/c36044481877e1684315cbfdaaafa1a87947b166/Filters/AWAvenue-Ads-Rule-QuantumultX.list#L1-L2 

希望可以修正

### 自查步骤

- [X] 我确认我已经详细阅读过[使用教程](https://awavenue.top/Knowledge.html)，且此问题并未在其中得到解决
- [X] 我确认此问题是由本项目规则引起或与其相关，请勿提交与本项目无关 Issue
- [X] 我确认此问题在本项目最新规则上依然存在，如因网络问题无法获取最新规则者还请自行解决
- [X] 我确认我已经搜索过 [Issue Tracker](https://github.com/TG-Twilight/AWAvenue-Ads-Rule/issues)，且并未查询到类似内容
- [X] 我确认本 Issue 只提及一个问题，如有多个问题，烦请提交多个 Issue

**Comment by heinu123** [comment]
你说得对，但是这是QuantumultX规则，不是clash

xiecang ***@***.***> 于 2024年5月12日周日 上午10:51写道：

**Comment by xiecang** [comment]
那使用 subconverter 转换的时候，应该用哪个呢？

**Comment by xiecang** [comment]
我没有装有 QuantumultX 的设备，按说 IP-CIDR 应该是类似的，大佬可以兼容一下吗？

**Comment by heinu123** [comment]
暂不支持subconverter配置文件，自行参考clashMeta文档[引入规则合集](https://wiki.metacubex.one/config/rule-providers/)

**Comment by heinu123** [comment]
你也可以查看[build分支](https://github.com/TG-Twilight/AWAvenue-Ads-Rule/tree/build)下的开发文档，编写subconverter配置文件转换插件

> 我没有装有 QuantumultX 的设备，按说 IP-CIDR 应该是类似的，大佬可以兼容一下吗？

**Comment by xiecang** [comment]
大佬戾气有点重哦，不要对提 issue 的人抱有那么重的敌意嘛

不选择 rule-providers 方式是我个人偏好，可能偶尔因为客户端版本或者网络问题 provider 不兼容或下载失败，我比较习惯服务端聚合后给出解析后的结果

我理解在这里
https://github.com/TG-Twilight/AWAvenue-Ads-Rule/blob/6cc145b92bc1e43c69649dc71f47e7312034402d/script/QuantumultX.py#L19
修改为
```python
        ip_lines = f"IP-CIDR,{line.strip()}/32,reject"
```
应该就可以了，大佬看看是不是这样

**Comment by TG-Twilight** [comment]
感谢你的提交，稍后我们会进行审查。

还有，东八区现在是饭点🤨

我们的协作者也要吃饭的。

**Comment by xiecang** [comment]
好的，辛苦大佬了，期待能支持~

**Comment by heinu123** [comment]
> 大佬戾气有点重哦，不要对提 issue 的人抱有那么重的敌意嘛
> 
> 不选择 rule-providers 方式是我个人偏好，可能偶尔因为客户端版本或者网络问题 provider 不兼容或下载失败，我比较习惯服务端聚合后给出解析后的结果
> 
> 我理解在这里
> 
> https://github.com/TG-Twilight/AWAvenue-Ads-Rule/blob/6cc145b92bc1e43c69649dc71f47e7312034402d/script/QuantumultX.py#L19
> 
> 
> 修改为
> ```python
>         ip_lines = f"IP-CIDR,{line.strip()}/32,reject"
> ```
> 
> 应该就可以了，大佬看看是不是这样

但是这是QuantumultX规则，与clash无关

**Comment by xiecang** [comment]
> > 大佬戾气有点重哦，不要对提 issue 的人抱有那么重的敌意嘛
> > 不选择 rule-providers 方式是我个人偏好，可能偶尔因为客户端版本或者网络问题 provider 不兼容或下载失败，我比较习惯服务端聚合后给出解析后的结果
> > 我理解在这里
> > https://github.com/TG-Twilight/AWAvenue-Ads-Rule/blob/6cc145b92bc1e43c69649dc71f47e7312034402d/script/QuantumultX.py#L19
> > 
> > 修改为
> > ```python
> >         ip_lines = f"IP-CIDR,{line.strip()}/32,reject"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 应该就可以了，大佬看看是不是这样
> 
> 但是这是QuantumultX规则，与clash无关

是没有关系，因为 subconverter 可以用这种格式，我正好这样误用了，如果大佬支持了 `IP/掩码` 这种写法，那正好就兼容了 clash 对 IP-CIDR 的格式要求，这个文件就也可以被 clash 使用了，可能这么用的人不多，给大佬添麻烦了~

**Comment by heinu123** [comment]
> > > 大佬戾气有点重哦，不要对提 issue 的人抱有那么重的敌意嘛
> > > 不选择 rule-providers 方式是我个人偏好，可能偶尔因为客户端版本或者网络问题 provider 不兼容或下载失败，我比较习惯服务端聚合后给出解析后的结果
> > > 我理解在这里
> > > https://github.com/TG-Twilight/AWAvenue-Ads-Rule/blob/6cc145b92bc1e43c69649dc71f47e7312034402d/script/QuantumultX.py#L19
> > > 
> > > 修改为
> > > ```python
> > >         ip_lines = f"IP-CIDR,{line.strip()}/32,reject"
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 应该就可以了，大佬看看是不是这样
> > 
> > 
> > 但是这是QuantumultX规则，与clash无关
> 
> 是没有关系，因为 subconverter 可以用这种格式，我正好这样误用了，如果大佬支持了 `IP/掩码` 这种写法，那正好就兼容了 clash 对 IP-CIDR 的格式要求，这个文件就也可以被 clash 使用了，可能这么用的人不多，给大佬添麻烦了~

插件不会处理`IP/掩码`，因为会有`/8' `/16` `/32` `/64` `/128` 我们会在基础规则上添加

**Comment by xiecang** [comment]
加个 if else 判断应该可行吧？ 我提个 pull request 吗？

**Comment by heinu123** [comment]
> 加个 if else 判断应该可行吧？ 我提个 pull request 吗？

不用，在基础规则上修改即可

**Comment by xiecang** [comment]
> > 加个 if else 判断应该可行吧？ 我提个 pull request 吗？
> 
> 不用，在基础规则上修改即可

好的，有劳大佬了，太感谢了~
