### ISSUE TITLE
[BUG] 百度输入法功能误拦截

### ISSUE THREAD

**Issue by Satiakura** [TG-Twilight/AWAvenue-Ads-Rule#76]
### 问题描述

拦截mime.baidu.com，导致手机百度输入法下载更多语言、神句配图、打字弹图等多种功能无法使用。望修复

### 自查步骤

- [X] 我确认我已经详细阅读过[使用教程](https://awavenue.top/Knowledge.html)，且此问题并未在其中得到解决
- [X] 我确认此问题是由本项目规则引起或与其相关，请勿提交与本项目无关 Issue
- [X] 我确认此问题在本项目最新规则上依然存在，如因网络问题无法获取最新规则者还请自行解决
- [X] 我确认我已经搜索过 [Issue Tracker](https://github.com/TG-Twilight/AWAvenue-Ads-Rule/issues)，且并未查询到类似内容
- [X] 我确认本 Issue 只提及一个问题，如有多个问题，烦请提交多个 Issue

**Comment by TG-Twilight** [comment]
However, this link will upload your input text. Its principle is to upload your input text to match it on the server side, and then send the corresponding picture.

**Comment by TG-Twilight** [comment]
You should check out #38

**Comment by TG-Twilight** [comment]
相对于大多数人而言，隐私开关并不会被注意到。为了保护隐私，我们认为保留这个域名是必要的，如果您实在是有需要，那么我们建议您自行在相关界面放行该域名。
