### ISSUE TITLE
[BUG] 误杀百度网盘网页端静态资源域名

### ISSUE THREAD

**Issue by xunpod** [TG-Twilight/AWAvenue-Ads-Rule#79]
### 问题描述

拦截 `staticsns.cdn.bcebos.com` 导致以下静态资源无法加载
```
https://staticsns.cdn.bcebos.com/amis/2024-7/1721794305951/zhuancun_bai.png
https://staticsns.cdn.bcebos.com/amis/2024-7/1721794305605/xiazai.png
https://staticsns.cdn.bcebos.com/amis/2024-7/1721802672148/checkbox.png
https://staticsns.cdn.bcebos.com/amis/2024-7/1721794305280/shouji.png
https://staticsns.cdn.bcebos.com/amis/2024-7/1722306339275/Rectangle.png
https://staticsns.cdn.bcebos.com/amis/2024-7/1721806895482/fileicon_dir.png
https://staticsns.cdn.bcebos.com/amis/2024-7/1722307813698/%E5%B7%B2%E8%AE%A2%E9%98%85.png
https://staticsns.cdn.bcebos.com/amis/2024-8/1722592402960/%E6%96%87%E4%BB%B6%E5%A4%B9%20(2).png
```
![image](https://github.com/user-attachments/assets/3887970c-0a22-4991-aa79-675fc7038f14)

### 复现步骤

测试时间：2024-08-21 13:30:00
AWAvenue Ads Rule Version: https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main/AWAvenue-Ads-Rule.txt
```
!Title: AWAvenue Ads Rule
!Last modified: 2024-07-23T09:36:03.160610+00:00
!--------------------------------------
!Total lines: 626
!Version: 1.5.0-release-Patch-2

!Homepage: https://github.com/TG-Twilight/AWAvenue-Ads-Rule
!License: https://github.com/TG-Twilight/AWAvenue-Ads-Rule/blob/main/LICENSE
```
测试用百度网盘分享链接：https://pan.baidu.com/s/1WDEs_nOKGSvNX7MWFbEFnw?pwd=65qu
![image](https://github.com/user-attachments/assets/3526efac-349e-4ab6-9468-1c060d83c98a)

### 问题截图

![image](https://github.com/user-attachments/assets/5ca24ce0-fa8e-4436-beaf-b6c86bdd5707)

![image](https://github.com/user-attachments/assets/5df17dc2-59bd-401e-81fa-f4a4a068709c)

### 自查步骤

- [X] 我确认我已经详细阅读过[使用教程](https://awavenue.top/Knowledge.html)，且此问题并未在其中得到解决
- [X] 我确认此问题是由本项目规则引起或与其相关，请勿提交与本项目无关 Issue
- [X] 我确认此问题在本项目最新规则上依然存在，如因网络问题无法获取最新规则者还请自行解决
- [X] 我确认我已经搜索过 [Issue Tracker](https://github.com/TG-Twilight/AWAvenue-Ads-Rule/issues)，且并未查询到类似内容
- [X] 我确认本 Issue 只提及一个问题，如有多个问题，烦请提交多个 Issue

**Comment by TG-Twilight** [comment]
@xunpod 好的我们会进行问题的排查，感谢提交

**Comment by TG-Twilight** [comment]
久等了，经过几天的实际测试，这个确实会影响百度网盘分享页的一些图片资源加载，但同时也拦截了百度的推广背景和手机端一些ad的图片加载。

被拦截的图片不会影响其正常使用，所以我们暂时认为这条域名应该继续保留。

**Comment by TG-Twilight** [comment]
已经修复，该域名迁移至“补充规则”中。
