### ISSUE TITLE
[BUG] Regex 拦截书写格式错误

### ISSUE THREAD

**Issue by ghitori** [TG-Twilight/AWAvenue-Ads-Rule#80]
### 问题描述

在 Adguard 主文件中，Regex 拦截类型的书写格式不正确导致条目未生效/错误生效

该问题也直接导致 Regex 在 sing-box 中报错 ``` missing argument to repetition operator: `*` ```

## 失效证明

使用 Adguard Edge 插件，在用户规则里仅添加`/*.shouji.sogou.com/`，并关闭其他所有过滤器

浏览器启用开发者选项网络监测&开启 Adguard 日志、

访问 [https://input.shouji.sogou.com](https://input.shouji.sogou.com) ，观察到网站图标正常加载

### 匹配当前及下级所有域名

修改用户规则为`/.*\.shouji\.sogou\.com/`

### 精准匹配每一级域名

修改用户规则为`/[^.]*\.shouji\.sogou\.com/`

以上两种方式访问 [https://input.shouji.sogou.com](https://input.shouji.sogou.com) ，皆可观察到网站图标被拦截

### 拦截失效
![image](https://github.com/user-attachments/assets/e0c42de9-c364-4e3e-9152-0ec96c00b88c)

### 下级匹配
![image](https://github.com/user-attachments/assets/4a9ab0b1-2727-482e-889b-c53369f8cb0a)

### 精确匹配
![image](https://github.com/user-attachments/assets/ac40e39a-c3e4-4419-aadf-67fe40f21954)

### 自查步骤

- [X] 我确认我已经详细阅读过[使用教程](https://awavenue.top/Knowledge.html)，且此问题并未在其中得到解决
- [X] 我确认此问题是由本项目规则引起或与其相关，请勿提交与本项目无关 Issue
- [X] 我确认此问题在本项目最新规则上依然存在，如因网络问题无法获取最新规则者还请自行解决
- [X] 我确认我已经搜索过 [Issue Tracker](https://github.com/TG-Twilight/AWAvenue-Ads-Rule/issues)，且并未查询到类似内容
- [x] 我确认本 Issue 只提及一个问题，如有多个问题，烦请提交多个 Issue

**Comment by TG-Twilight** [comment]
好的，这个问题之后会得到解决。

**Comment by yyyr-otz** [comment]
initialize rule-set[7]: initial rule-set:geosite-ad:parse rule_set.rules.[0]: domain_regex: parse expression0: error parsing regexp:missingargument to repetition operator: '*'

我还以为是我导入错误了233

**Comment by TG-Twilight** [comment]
> initialize rule-set[7]: initial rule-set:geosite-ad:parse rule_set.rules.[0]: domain_regex: parse expression0: error parsing regexp:missingargument to repetition operator: '*'
> 
> 我还以为是我导入错误了233

你没有错，有错的是规则。🥲
