### ISSUE TITLE
[BUG] adgurdhome 规则导致 起点读书app IOS端，网络连接异常

### ISSUE THREAD

**Issue by sky540** [TG-Twilight/AWAvenue-Ads-Rule#81]
### 问题描述

adgurdhome 规则导致IOS端，网络连接异常。安卓端正常

### 复现步骤

在adgurdhome 去掉规则，起点读书IOS端APP网络就正常了。这个问题不影响安卓端

### 自查步骤

- [X] 我确认我已经详细阅读过[使用教程](https://awavenue.top/Knowledge.html)，且此问题并未在其中得到解决
- [X] 我确认此问题是由本项目规则引起或与其相关，请勿提交与本项目无关 Issue
- [X] 我确认此问题在本项目最新规则上依然存在，如因网络问题无法获取最新规则者还请自行解决
- [X] 我确认我已经搜索过 [Issue Tracker](https://github.com/TG-Twilight/AWAvenue-Ads-Rule/issues)，且并未查询到类似内容
- [X] 我确认本 Issue 只提及一个问题，如有多个问题，烦请提交多个 Issue

**Comment by TG-Twilight** [comment]
@sky540 那你可以提供导致异常的域名吗？这个你可以在AdGuard日志中查看。


日志的提供将直接关系到这个问题能否被解决。

**Comment by sky540** [comment]
> @sky540 那你可以提供导致异常的域名吗？这个你可以在AdGuard日志中查看。
> 
> 日志的提供将直接关系到这个问题能否被解决。

magev6.if.qidian.com  这个被拦截了

**Comment by TG-Twilight** [comment]
好的，感谢你的提交，这个问题得到解决时，这个issue将会被一同关闭。 😁

**Comment by TG-Twilight** [comment]
fix
