### ISSUE TITLE
[BUG] 搜狗输入法规则重复

### ISSUE THREAD

**Issue by kanao7** [TG-Twilight/AWAvenue-Ads-Rule#85]
### 问题描述

Clash-classical.yaml中
513行`  - DOMAIN,shouji.sogou.com`
645行`  - DOMAIN,ws-keyboard.shouji.sogou.com`
668行`  - DOMAIN-REGEX,^*\.*\.shouji\.sogou\.com$`
673行`  - DOMAIN-REGEX,^*\.shouji\.sogou\.com$`
第四条匹配包含第二、三条，第一条加第四条等同于`DOMAIN-SUFFIX,shouji.sogou.com`，建议直接写DOMAIN-SUFFIX
另外，[常见问题](https://awavenue.top/Knowledge.html#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-%E4%B8%8E%E7%AD%94%E7%96%91)中搜狗的放行域名错了，是`shouji.sogou.com`而不是`shouji.sougou.com`

### 自查步骤

- [X] 我确认我已经详细阅读过[使用教程](https://awavenue.top/Knowledge.html)，且此问题并未在其中得到解决
- [X] 我确认此问题是由本项目规则引起或与其相关，请勿提交与本项目无关 Issue
- [X] 我确认此问题在本项目最新规则上依然存在，如因网络问题无法获取最新规则者还请自行解决
- [X] 我确认我已经搜索过 [Issue Tracker](https://github.com/TG-Twilight/AWAvenue-Ads-Rule/issues)，且并未查询到类似内容
- [X] 我确认本 Issue 只提及一个问题，如有多个问题，烦请提交多个 Issue

**Comment by TG-Twilight** [comment]
你好，感谢反馈。

首先“shouji.sougou.com”也是一条域名，并且是可用的。

![image](https://github.com/user-attachments/assets/b856fbd3-fbc8-40ed-9c86-cb37b4506f8d)

对于重复的问题：

部分设备是不适配正则的，所以为了最大限度之有效过滤，我们会写两种，并且一般书写法优先级大于正则。
下次更新时将会移除“ws-keyboard.shouji.sogou.com”。


若无其他问题，此issue会在下次更新时关闭，在此之前，您亦可自行关闭。


祝你生活愉快！

**Comment by kanao7** [comment]
> 你好，感谢反馈。
> 
> 首先“shouji.sougou.com”也是一条域名，并且是可用的。
> 
> ![image](https://private-user-images.githubusercontent.com/121682528/368879031-b856fbd3-fbc8-40ed-9c86-cb37b4506f8d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3MzA3MzYsIm5iZiI6MTcyNjczMDQzNiwicGF0aCI6Ii8xMjE2ODI1MjgvMzY4ODc5MDMxLWI4NTZmYmQzLWZiYzgtNDBlZC05Yzg2LWNiMzdiNDUwNmY4ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOVQwNzIwMzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZjA2MTAyOWU0NTQ3ZmY2OGY3ZTJlNTZkYzJjY2E1ZGRmMWJjODJiY2JlMzQyMDBhMjBhMmZhZDE4NTc3OWZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qV3GTdWXBJJAbVmdDTmcubixDCkVIP7Ay2e7OQaxOqA)
> 
> 对于重复的问题：
> 
> 部分设备是不适配正则的，所以为了最大限度之有效过滤，我们会写两种，并且一般书写法优先级大于正则。 下次更新时将会移除“ws-keyboard.shouji.sogou.com”。
> 
> 若无其他问题，此issue会在下次更新时关闭，在此之前，您亦可自行关闭。
> 
> 祝你生活愉快！
`shouji.sougou.com`这压根就不是搜狗的域名，拦截规则里写的也是shouji.**sogou**.com。
他官网写着
> 这是一个公益的宠物小站，名自“搜狗”的标准汉语拼音。2003年创立，与其它公司/商标无关。这里只有猫猫狗狗，没有险恶江湖。在这疫病流行期间，请照顾好您的宠物和您自己。

> 部分设备是不适配正则的，所以为了最大限度之有效过滤，不适配正则不更应该直接写domain-suffix吗

**Comment by kanao7** [comment]
@TG-Twilight 
> 首先“shouji.sougou.com”也是一条域名，并且是可用的。
`shouji.sougou.com`这就不是搜狗的域名，拦截规则里写的也是shouji.**sogou**.com。
他官网写着 _这是一个公益的宠物小站，名自“搜狗”的标准汉语拼音。2003年创立，与其它公司/商标无关。这里只有猫猫狗狗，没有险恶江湖。在这疫病流行期间，请照顾好您的宠物和您自己。_

> 部分设备是不适配正则的，所以为了最大限度之有效过滤
不适配正则不更应该直接写domain-suffix吗

**Comment by TG-Twilight** [comment]
好的，将会修正该错误，同时移除正则内容。
