### ISSUE TITLE
[enhancement] <提交拦截域名>

### ISSUE THREAD

**Issue by kanao7** [TG-Twilight/AWAvenue-Ads-Rule#86]
### 域名

abtest-ch.snssdk.com
gecko.snssdk.com
tobapplog.ctobsnssdk.com # 数据分析
adx-bj.anythinktech.com
adx-bj-req.anythinktech.com
adx-os.anythinktech.com
adx-os-req.anythinktech.com
cn-api.anythinktech.com
datk.anythinktech.com # 库里有 adx-cn.anythinktech.com
android.bugly.qq.com # 腾讯端质量监控平台
api-access.pangolin-sdk-toutiao-b.com # 库里有 api-access.pangolin-sdk-toutiao.com
bes-mtj.baidu.com #百度移动统计
dspsdk.pinduoduo.com #pdd
grs.dbankcloud.cn # 库里有 grs.dbankcloud.com
lf6-ad-union-sdk.pglstatp-toutiao.com # ad
promotion-partner.kuaishou.com # 快手推荐官平台
telecome.cn # 北京数字精准广告有限公司
unioncom.cc # 北京数字精准广告有限公司
tnc0-aliec2.zijieapi.com
tnc3-aliec2.zijieapi.com # 库里有 tnc3-aliec1.toutiaoapi.com
v2mi.gdt.qq.com
v3.gdt.qq.com # 腾讯社交联盟广告

### 效果说明

酷安抓的一些广告和信息收集域名

### 自查步骤

- [X] 我确认此拦截域名在本项目最新规则上并不存在，如因网络问题无法获取最新规则者还请自行解决
- [X] 我确认我已经搜索过 [Issue Tracker](https://github.com/TG-Twilight/AWAvenue-Ads-Rule/issues)，且并未查询到提交相同拦截域名的 Issue

**Comment by TG-Twilight** [comment]
@kanao7 非常谢谢你的提交！

我们会在核实后将其添加进规则中，感谢！

祝你生活愉快！😃
