### ISSUE TITLE
求添加这2个动漫网站的广告拦截

### ISSUE THREAD

**Issue by oldsento** [TG-Twilight/AWAvenue-Ads-Rule#89]
### 域名

http://qiqidm7.com/
https://www.tt776b.com/

### 效果说明

![IMG_20241013_181143.jpg](https://github.com/user-attachments/assets/e8701138-4b99-49eb-ad86-dc582ce6a761)

![IMG_20241013_175726](https://github.com/user-attachments/assets/ecf4e70a-1655-4a72-a591-d6aec52fd59d)
![IMG_20241013_175726.jpg](https://github.com/user-attachments/assets/d8c9bde1-88fb-4f8d-8139-a699cdb31e71)

这两个网站的广告机制好像是一样的，有GIF还有隐藏的几乎透明的切片广告图层，这个怎么也拦截不了全部，虽然可以手动标记但非常麻烦，

### 自查步骤

- [X] 我确认此拦截域名在本项目最新规则上并不存在，如因网络问题无法获取最新规则者还请自行解决
- [X] 我确认我已经搜索过 [Issue Tracker](https://github.com/TG-Twilight/AWAvenue-Ads-Rule/issues)，且并未查询到提交相同拦截域名的 Issue

**Comment by TG-Twilight** [comment]
这里不是许愿池孩子，而且这是网页广告，你最好使用浏览器插件/脚本拦截。
