### ISSUE TITLE
升级 sing-box 的配置字段 version 到 2

### ISSUE THREAD

**Issue by Sentsuki** [TG-Twilight/AWAvenue-Ads-Rule#90]
### 问题描述

根据 [https://sing-box.sagernet.org/configuration/rule-set/source-format/#compile](url) 所述，升级到 2 可以优化内存占用。
应该修改以下文件即可。
修改 `script/Singbox.py` 和 `script/Singbox-regex.py` 的 `"version": 1,` 字段，然后升级 `.github/workflows/build.yaml` 的 `wget -O ./sing-box.tar.gz https://github.com/SagerNet/sing-box/releases/download/v1.8.2/sing-box-1.8.2-linux-amd64.tar.gz` 到1.10.0版本以上。

### 自查步骤

- [x] 我确认我已经详细阅读过[使用教程](https://awavenue.top/Knowledge.html)，且此问题并未在其中得到解决
- [X] 我确认此问题是由本项目规则引起或与其相关，请勿提交与本项目无关 Issue
- [X] 我确认此问题在本项目最新规则上依然存在，如因网络问题无法获取最新规则者还请自行解决
- [X] 我确认我已经搜索过 [Issue Tracker](https://github.com/TG-Twilight/AWAvenue-Ads-Rule/issues)，且并未查询到类似内容
- [X] 我确认本 Issue 只提及一个问题，如有多个问题，烦请提交多个 Issue

**Comment by Mosney** [comment]
Since 1.10.0, the optimization is always applied to source rule-sets even if version is set to 1.

It is recommended to upgrade to 2 after sing-box 1.10.0 becomes a stable version.
