### ISSUE TITLE
[BUG] 拦截 henzanapp.com 导致好物清单App异常

### ISSUE THREAD

**Issue by Mosney** [TG-Twilight/AWAvenue-Ads-Rule#92]
### 问题描述

拦截 henzanapp.com 导致[好物清单](https://www.qingdan.com/download)App异常

### 复现步骤

完全无法加载内容

### 自查步骤

- [X] 我确认我已经详细阅读过[使用教程](https://awavenue.top/Knowledge.html)，且此问题并未在其中得到解决
- [X] 我确认此问题是由本项目规则引起或与其相关，请勿提交与本项目无关 Issue
- [X] 我确认此问题在本项目最新规则上依然存在，如因网络问题无法获取最新规则者还请自行解决
- [X] 我确认我已经搜索过 [Issue Tracker](https://github.com/TG-Twilight/AWAvenue-Ads-Rule/issues)，且并未查询到类似内容
- [X] 我确认本 Issue 只提及一个问题，如有多个问题，烦请提交多个 Issue

**Comment by Mosney** [comment]
稍等，我需要进一步确认一下

**Comment by Mosney** [comment]
还有商品页底部的Tab按钮也会被屏蔽，切无屏蔽网络加载一下以后就没问题了，所以就懒得找了。

**Comment by Mosney** [comment]
查了一下，`henzanapp.com` 最早是 https://github.com/TG-Twilight/AWAvenue-Ads-Rule/commit/de6a69398a6e9c7644e013cbc6659c02ed37529f 引入的

**Comment by chengnan049** [comment]
离谱

**Comment by TG-Twilight** [comment]
好的，这个域名将会移除。
