### ISSUE TITLE
关于点击即开的触摸类gif广告

### ISSUE THREAD

**Issue by iforgiveu** [TG-Twilight/AWAvenue-Ads-Rule#94]
### 问题描述

也不算是提交bug吧但讨论类型就只给两种。
在某些动漫电影类的网站里比如本例的https://www.yhdm9.cc里，屏幕下方普遍存在着该种嵌套多层的gif加多个小透明片组合层加白透明版层的悬浮条广告，不管点了哪一层都会直接跳转广告网站。
基于via，x等支持规则，脚本的浏览器，
我尝试使用各个订阅规则包括aw的进行屏蔽，都没有个能屏蔽小透明片的第二层和透明板的第三层的，其中，aw连gif的第一层都没有屏蔽，也没有拦截所跳转的广告网站。使用广告标记功能小透明片会消失一会儿但刷新页面后又重新出现，使用自建规则
.cn:8005/cc/*?is_not=
www.yhdm9.cc###div[style="position:fixed; bottom:*vw; left:*vw; z-index:*;display:block;width:*.6vw;height:*vw;background: #000;opacity:0.01;"]等不知为何也不能去除小透明片，仅能做到拦截网址。
从html源码可看出是使用脚本navigator.platform)){var i=0;for(var n=0;n<4;n++){for(var j=0;j<10;j++等函数生成小透明片及透明板层并加上监听事件而形成的，下载其html并注释掉相关源代码后本地查看发现这类广告消失了。遂我尝试使用脚本尝试修改相关代码的读取，但发现没什么用，似乎改不了在线的源码。
所以，能加上屏蔽这类广告各层的规则吗，或者，请告诉我怎么写屏蔽其的规则或脚本

### 问题截图

![Screenshot_2024-11-08-07-33-51-596_mark via](https://github.com/user-attachments/assets/f17db5be-d272-4dfc-8750-9b28cc95b839)
![Screenshot_2024-11-08-07-33-57-356_mark via](https://github.com/user-attachments/assets/a4b58c49-efe1-4855-92e5-950acb0a4c7d)
![Screenshot_2024-11-08-07-40-39-992_mark via](https://github.com/user-attachments/assets/780330c3-5b1a-4e08-91d7-facd024b3752)
![Screenshot_2024-11-08-07-40-47-838_mark via](https://github.com/user-attachments/assets/911c14bd-d8c1-4fae-8490-bc1550fa8dfc)
![Uploading Screenshot_2024-11-08-07-47-05-074_bin.mt.plus.canary.jpg…]()
![Screenshot_2024-11-08-08-00-22-508_mark via](https://github.com/user-attachments/assets/1c326822-eda9-4838-92ac-1bb24bf832d8)

### 自查步骤

- [X] 我确认我已经详细阅读过[使用教程](https://awavenue.top/Knowledge.html)，且此问题并未在其中得到解决
- [X] 我确认此问题是由本项目规则引起或与其相关，请勿提交与本项目无关 Issue
- [X] 我确认此问题在本项目最新规则上依然存在，如因网络问题无法获取最新规则者还请自行解决
- [X] 我确认我已经搜索过 [Issue Tracker](https://github.com/TG-Twilight/AWAvenue-Ads-Rule/issues)，且并未查询到类似内容
- [X] 我确认本 Issue 只提及一个问题，如有多个问题，烦请提交多个 Issue

**Comment by TG-Twilight** [comment]
你好，这种广告是来自于恶意配置的联盟广告。

根据你的描述，此广告js会在进入任意页面时创建一个全屏的透明广告来获取收益，这已经不是本广告规则可以处理的范围，我们针对的更多是来自广告sdk的广告而不是此类型的广告。

因此我建议你使用相应的油猴脚本或者是mitm之类的方式去拦截这个广告。
