### ISSUE TITLE
[enhancement] <提交拦截域名>

### ISSUE THREAD

**Issue by wartaiwan24** [TG-Twilight/AWAvenue-Ads-Rule#99]
### 域名

hisuggestion-drcn.ai.dbankcloud.cn
log-auth.zztfly.com
`||*zhihu-web-analytics.zhihu.com*`
`||*cm.bilibili.com*`

### 效果说明

hisuggestion-drcn.ai.dbankcloud.cn是华为手机里的跟踪器
log-auth.zztfly.com是知乎的
`||*zhihu-web-analytics.zhihu.com*`   也是知乎的，如果规则中存在||zhihu-web-analytics.zhihu.com，就用 `||*zhihu-web-analytics.zhihu.com*` 替换，因为知乎会用IP绕过规则，所以需要使用上通配符 

`||*cm.bilibili.com*`  同理也是，是为了阻止哔哩哔哩绕过规则，所以加上通配符

### 自查步骤

- [X] 我确认此拦截域名在本项目最新规则上并不存在，如因网络问题无法获取最新规则者还请自行解决
- [X] 我确认我已经搜索过 [Issue Tracker](https://github.com/TG-Twilight/AWAvenue-Ads-Rule/issues)，且并未查询到提交相同拦截域名的 Issue

**Comment by TG-Twilight** [comment]
首先感谢你的好意。

“hisuggestion-drcn.ai.dbankcloud.cn”是之前我们曾经添加过的，添加了之后可以拦截少量的广告但是会造成一些服务的不可用，例如华为运动的勋章无法加载之类。

其次，“cm.bilibili.com”就你上一个issue提过 #97 ，我认为根本没有查看相关的说明，拦截此域名会造成一些第三方客户端无法正常观看视频。

最后，对于如何贡献规则我们也有相应的详细说明，在build分支里，请自行查看而不是直接给成品的规则pr。
